import { createConfig, http } from "wagmi";
import {
  mainnet,
  sepolia,
  goerli,
  polygon,
  polygonMumbai,
  bsc,
  bscTestnet,
  arbitrum,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  optimism,
  optimismSepolia,
  fantom,
  gnosis,
  moonbeam,
  moonriver,
  linea,
  base,
  zora,
  zkSync,
  scroll,
  scrollSepolia,
  localhost,
} from 'wagmi/chains'


export const config = createConfig({
  chains: [
    mainnet,
    sepolia,
    goerli,
    polygon,
    polygonMumbai,
    bsc,
    bscTestnet,
    arbitrum,
    arbitrumSepolia,
    avalanche,
    avalancheFuji,
    optimism,
    optimismSepolia,
    fantom,
    gnosis,
    moonbeam,
    moonriver,
    linea,
    base,
    zora,
    zkSync,
    scroll,
    scrollSepolia,
    localhost,
  ],
  transports: {
    [mainnet.id]: http(),
    [sepolia.id]: http(),
    [goerli.id]: http(),
    [polygon.id]: http(),
    [polygonMumbai.id]: http(),
    [bsc.id]: http(),
    [bscTestnet.id]: http(),
    [arbitrum.id]: http(),
    [arbitrumSepolia.id]: http(),
    [avalanche.id]: http(),
    [avalancheFuji.id]: http(),
    [optimism.id]: http(),
    [optimismSepolia.id]: http(),
    [fantom.id]: http(),
    [gnosis.id]: http(),
    [moonbeam.id]: http(),
    [moonriver.id]: http(),
    [linea.id]: http(),
    [base.id]: http(),
    [zora.id]: http(),
    [zkSync.id]: http(),
    [scroll.id]: http(),
    [scrollSepolia.id]: http(),
    [localhost.id]: http(),
  },
})
