import { useWriteContract, useWaitForTransactionReceipt, useChainId } from "wagmi";
import { Abi, Address } from 'viem';

import {
    // These are assumed to be generated by wagmi/viem/typechain
    grimStakeAddress,
    grimStakeAbi,
} from "@/src/generated";

/**
 * @dev Custom hook to handle unstaking/withdrawing tokens.
 */
export function useUnstake() {
    const chainId = useChainId();
    // Assuming GRIM_STAKE_ADDRESS is correctly indexed by number chainId
    const contractAddress = grimStakeAddress[chainId as keyof typeof grimStakeAddress]
    // Extracting the ABI array from the imported JSON artifact
    const {
        data: hash,
        writeContract,
        isPending: isWritePending,
        error: writeError
    } = useWriteContract();

    const {
        isLoading: isConfirming,
        isSuccess: isConfirmed,
        error: confirmationError
    } = useWaitForTransactionReceipt({ hash });

    /**
     * Helper function to execute the unstake transaction.
     * @param tokenAddress The address of the staked token.
     * @param amount The amount of tokens to unstake (in smallest units/wei).
     */
    const unstake = (tokenAddress: Address, amount: bigint) => {
        if (!contractAddress) {
            console.error("GrimStake contract address not found for current chain.");
            return;
        }

        writeContract({
            address: contractAddress as Address,
            abi: grimStakeAbi as Abi,
            functionName: 'unstake',
            args: [tokenAddress, amount],
        });
    };

    return {
        unstake,
        hash,
        isWriting: isWritePending,
        isConfirming,
        isConfirmed,
        error: writeError || confirmationError,
    };
}